peer:
  id: p1.peerOrg1
  networkId: dev
  listenAddress: 0.0.0.0:7051
  address: p1.peerOrg1:7051
  addressAutoDetect: false
  gateway:
    enabled: true
    endorsementTimeout: 30s
    broadcastTimeout: 30s
    dialTimeout: 2m
  keepalive:
    interval: 7200s
    timeout: 20s
    minInterval: 60s
    client:
      interval: 60s
      timeout: 20s
    deliveryClient:
      interval: 60s
      timeout: 20s
  gossip:
    bootstrap: p0.peerOrg1:7051
    useLeaderElection: true
    orgLeader: true
    membershipTrackerInterval: 5s
    endpoint: p1.peerOrg1:7051
    maxBlockCountToStore: 10
    maxPropagationBurstLatency: 10ms
    maxPropagationBurstSize: 10
    propagateIterations: 1
    propagatePeerNum: 3
    pullInterval: 4s
    pullPeerNum: 3
    requestStateInfoInterval: 4s
    publishStateInfoInterval: 4s
    stateInfoRetentionInterval: null
    publishCertPeriod: 10s
    skipBlockVerification: false
    dialTimeout: 3s
    connTimeout: 2s
    recvBuffSize: 20
    sendBuffSize: 200
    digestWaitTime: 1s
    requestWaitTime: 1500ms
    responseWaitTime: 2s
    aliveTimeInterval: 5s
    aliveExpirationTimeout: 25s
    reconnectInterval: 25s
    maxConnectionAttempts: 120
    msgExpirationFactor: 20
    externalEndpoint: p1.peerOrg1:7051
    election:
      startupGracePeriod: 15s
      membershipSampleInterval: 1s
      leaderAliveThreshold: 10s
      leaderElectionDuration: 5s
    pvtData:
      implicitCollectionDisseminationPolicy:
        requiredPeerCount: 1
        maxPeerCount: 1
    state:
      enabled: false
  tls:
    enabled: true
    clientAuthRequired: false
    cert:
      file: /etc/hyperledger/fabric/tls/cert.pem
    key:
      file: /etc/hyperledger/fabric/tls/key
    rootcert:
      file: /etc/hyperledger/fabric/tls/tls-ca-cert.pem
    clientRootCAs:
      files:
      - tls/ca.crt
    clientKey:
      file: null
    clientCert:
      file: null
  authentication:
    timewindow: 15m
  fileSystemPath: /var/hyperledger/production/p1.peerOrg1
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore: ''
    PKCS11:
      Library: null
      Label: null
      Pin: null
      Hash: null
      Security: null
      SoftwareVerify: null
      Immutable: null
      AltID: null
      KeyIds: null
  mspConfigPath: /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchainProva/organizations/peerOrganizations/peerOrg1/peersp1.peerOrg1/msp
  localMspId: SampleOrg
  client:
    connTimeout: 3s
  deliveryclient:
    blockGossipEnabled: false
    reconnectTotalTimeThreshold: 3600s
    connTimeout: 3s
    reConnectBackoffThreshold: 3600s
    blockCensorshipTimeoutKey: 30s
    minimalReconnectInterval: 100ms
    addressOverrides: null
    policy: cluster
  localMspType: bccsp
  profile:
    enabled: false
    listenAddress: 0.0.0.0:6060
  handlers:
    authFilters:
    - name: DefaultAuth
    - name: ExpirationCheck
    decorators:
    - name: DefaultDecorator
    endorsers:
      escc:
        name: DefaultEndorsement
        library: null
    validators:
      vscc:
        name: DefaultValidation
        library: null
  validatorPoolSize: null
  discovery:
    enabled: true
    authCacheEnabled: true
    authCacheMaxSize: 1000
    authCachePurgeRetentionRatio: 0.75
    orgMembersAllowedAccess: false
  limits:
    concurrency:
      endorserService: 2500
      deliverService: 2500
      gatewayService: 500
  maxRecvMsgSize: 104857600
  maxSendMsgSize: 104857600
  chaincodeListenAddress: 0.0.0.0:7052
  chaincodeAddress: p1.peerOrg1:7052
  chaincode:
    externalBuilders: null
vm:
  endpoint: unix:///var/run/docker.sock
  docker:
    tls:
      enabled: false
      ca:
        file: docker/ca.crt
      cert:
        file: docker/tls.crt
      key:
        file: docker/tls.key
    attachStdout: false
    hostConfig:
      NetworkMode: host
      Dns: null
      LogConfig:
        Type: json-file
        Config:
          max-size: 50m
          max-file: '5'
      Memory: 2147483648
chaincode:
  id:
    path: null
    name: null
  builder: $(DOCKER_NS)/fabric-ccenv:$(TWO_DIGIT_VERSION)
  pull: false
  golang:
    runtime: $(DOCKER_NS)/fabric-baseos:$(TWO_DIGIT_VERSION)
    dynamicLink: false
  java:
    runtime: $(DOCKER_NS)/fabric-javaenv:2.5
  node:
    runtime: $(DOCKER_NS)/fabric-nodeenv:2.5
  externalBuilders:
  - name: ccaas_builder
    path: /opt/hyperledger/ccaas_builder
    propagateEnvironment:
    - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG
  installTimeout: 300s
  startuptimeout: 300s
  executetimeout: 30s
  mode: net
  keepalive: 0
  system:
    _lifecycle: enable
    cscc: enable
    lscc: enable
    qscc: enable
  logging:
    level: info
    shim: warning
    format: '%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc}
      -> %{level:.4s} %{id:03x}%{color:reset} %{message}'
  runtimeParams:
    useWriteBatch: true
    maxSizeWriteBatch: 1000
    useGetMultipleKeys: true
    maxSizeGetMultipleKeys: 1000
ledger:
  blockchain: null
  state:
    stateDatabase: CouchDB
    totalQueryLimit: 100000
    couchDBConfig:
      couchDBAddress: couchdb:5984
      username: admin
      password: adminPsw
  history:
    enableHistoryDatabase: true
  pvtdataStore:
    collElgProcMaxDbBatchSize: 5000
    collElgProcDbBatchesInterval: 1000
    deprioritizedDataReconcilerInterval: 60m
    purgeInterval: 100
    purgedKeyAuditLogging: true
  snapshots:
    rootDir: /var/hyperledger/production/snapshots
operations:
  listenAddress: 127.0.0.1:9443
  tls:
    enabled: false
metrics:
  provider: prometheus
  statsd:
    network: udp
    address: 127.0.0.1:8125
    writeInterval: 10s
    prefix: null
