version: '3'
services:
  ca_server:
    image: hyperledger/fabric-ca:1.5.15
    container_name: tls-ca
    ports:
    - 7054:7054
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-server
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tls-ca-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/fabric-ca-server-tls/msp/keystore:/etc/hyperledger/fabric-ca-server-config
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/fabric-ca-server-tls/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    command: sh -c 'fabric-ca-server start -badmin:adminPsw -d'
  fabric-ca-server-org1:
    image: hyperledger/fabric-ca:1.5.15
    container_name: org-ca
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=org-ca
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls/cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls/ORG1_PRIVATE_KEY
    ports:
    - 7055:7055
    command: sh -c 'fabric-ca-server start -b admin:adminPsw -d'
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/fabric-ca-server-org1:/etc/hyperledger/fabric-ca-server
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/fabric-ca-server-org1/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
  Host1:
    container_name: Host1
    image: hyperledger/fabric-orderer
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/fabric/config
    - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/msp
    - ORDERER_GENERAL_LOCALMSPID=SampleOrg
    - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
    - ORDERER_GENERAL_BOOTSTRAPFILE=/etc/hyperledger/fabric/config/genesis_block.pb
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/orderers_bin/Host1/config:/etc/hyperledger/fabric/config
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/organizations/ordererOrganizations/Consenters/orderers/Host1/msp:/etc/hyperledger/fabric/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/organizations/ordererOrganizations/Consenters/orderers/Host1/tls:/etc/hyperledger/fabric/tls
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/organizations/ordererOrganizations/Consenters/orderers/Host1/ledger:/var/hyperledger/production/orderer
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/organizations/ordererOrganizations/Consenters/orderers/Host1/keys:/etc/hyperledger/fabric/keys
    ports:
    - 7080
    command: orderer
  Host2:
    container_name: Host2
    image: hyperledger/fabric-orderer
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/fabric/config
    - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/msp
    - ORDERER_GENERAL_LOCALMSPID=SampleOrg
    - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
    - ORDERER_GENERAL_BOOTSTRAPFILE=/etc/hyperledger/fabric/config/genesis_block.pb
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/orderers_bin/Host2/config:/etc/hyperledger/fabric/config
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/organizations/ordererOrganizations/Consenters/orderers/Host2/msp:/etc/hyperledger/fabric/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/organizations/ordererOrganizations/Consenters/orderers/Host2/tls:/etc/hyperledger/fabric/tls
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/organizations/ordererOrganizations/Consenters/orderers/Host2/ledger:/var/hyperledger/production/orderer
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/organizations/ordererOrganizations/Consenters/orderers/Host2/keys:/etc/hyperledger/fabric/keys
    ports:
    - 7081
    command: orderer
  Host3:
    container_name: Host3
    image: hyperledger/fabric-orderer
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/fabric/config
    - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/msp
    - ORDERER_GENERAL_LOCALMSPID=SampleOrg
    - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
    - ORDERER_GENERAL_BOOTSTRAPFILE=/etc/hyperledger/fabric/config/genesis_block.pb
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/orderers_bin/Host3/config:/etc/hyperledger/fabric/config
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/organizations/ordererOrganizations/Consenters/orderers/Host3/msp:/etc/hyperledger/fabric/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/organizations/ordererOrganizations/Consenters/orderers/Host3/tls:/etc/hyperledger/fabric/tls
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/organizations/ordererOrganizations/Consenters/orderers/Host3/ledger:/var/hyperledger/production/orderer
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/organizations/ordererOrganizations/Consenters/orderers/Host3/keys:/etc/hyperledger/fabric/keys
    ports:
    - 7082
    command: orderer
