version: '3'
services:
  ca_server:
    image: hyperledger/fabric-ca:1.5
    container_name: ca_server
    ports:
    - 7054:7054
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-server
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tls-ca-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Prova/fabric-ca-server/msp/keystore:/etc/hyperledger/fabric-ca-server-config
    command: sh -c 'fabric-ca-server start -badmin:adminpwd -d'
  fabric-ca-server-org1:
    image: hyperledger/fabric-ca
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=org1
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    ports:
    - 7055:7055
    command: sh -c 'fabric-ca-server start -b admin:adminpwd -d'
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Provafabric-ca-server-org1/msp/keystore:/etc/hyperledger/fabric-ca-server
