General:
  ListenAddress: 0.0.0.0
  ListenPort: 7050
  TLS:
    Enabled: true
    PrivateKey: /etc/hyperledger/fabric/tls/key
    Certificate: /etc/hyperledger/fabric/tls/cert.pem
    RootCAs:
    - tls/ca.crt
    ClientAuthRequired: true
    ClientRootCAs:
    - /etc/hyperledger/fabric/tls/tls-ca-cert.pem
  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s
  Cluster:
    SendBufferSize: 100
    ClientCertificate: null
    ClientPrivateKey: null
    ListenPort: null
    ListenAddress: null
    ServerCertificate: null
    ServerPrivateKey: null
    ReplicationPolicy: null
  LocalMSPDir: /etc/hyperledger/fabric/msp
  LocalMSPID: SampleOrg
  Profile:
    Enabled: false
    Address: 0.0.0.0:6060
  BCCSP:
    Default: SW
    SW:
      FileKeyStore:
        KeyStore: $(pwd)/Prova/organizations/ordererOrganizations/ordererOrg/orderers/ord1.ordererOrg/msp/keystore
      Hash: SHA2
      Security: 256
    PKCS11:
      Library: null
      Label: null
      Pin: null
      Hash: null
      Security: null
      FileKeyStore:
        KeyStore: null
  Authentication:
    TimeWindow: 15m
FileLedger:
  Location: $(pwd)/Prova/organizations/ordererOrganizations/ordererOrg/orderers/ord1.ordererOrg/fileLedger
Debug:
  BroadcastTraceDir: null
  DeliverTraceDir: null
Operations:
  ListenAddress: 127.0.0.1:8443
  TLS:
    Enabled: false
    Certificate: null
    PrivateKey: null
    ClientAuthRequired: false
    ClientRootCAs: [
      ]
Metrics:
  Provider: disabled
  Statsd:
    Network: udp
    Address: 127.0.0.1:8125
    WriteInterval: 30s
    Prefix: null
Admin:
  ListenAddress: 127.0.0.1:9443
  TLS:
    Enabled: true
    Certificate: $(pwd)/Prova/organizations/ordererOrganizations/ordererOrg/orderers/ord1.ordererOrg/msp/keystore/
    PrivateKey: $(pwd)/Prova/organizations/ordererOrganizations/ordererOrg/orderers/ord1.ordererOrg/msp/keystore/server.key
    ClientAuthRequired: true
    ClientRootCAs:
    - /etc/hyperledger/fabric/tls/tls-ca-cert.pem
ChannelParticipation:
  Enabled: false
  MaxRequestBodySize: 1 MB
Consensus:
  WALDir: /var/hyperledger/production/orderer/etcdraft/wal
  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
